/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.IControlador;
import DTO.DTOAmortizacion;
import DTO.DTOCliente;
import Data.Lector;
import Modelo.Factorys.*;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdom2.JDOMException;

/**
 *
 * @author Mellvin
 */
public class VistaGUI extends javax.swing.JFrame {

    /**
     * Creates new form VistaGUI
     */
    public VistaGUI() throws IOException, JDOMException {
        initComponents();
        SetMonedas();
        SetAmortizacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cNombre = new javax.swing.JTextField();
        cPA = new javax.swing.JTextField();
        cPlazo = new javax.swing.JTextField();
        cSA = new javax.swing.JTextField();
        cIA = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cMonto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaResultados = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cltNombre = new javax.swing.JLabel();
        JrMonto = new javax.swing.JLabel();
        jrPlazo = new javax.swing.JLabel();
        jrIA = new javax.swing.JLabel();
        jrAmortizacion = new javax.swing.JLabel();
        labelChuky = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelTipoCambio = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sistema de Amortizacion");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Primer Apellido:");

        jLabel4.setText("Segundo Apellido:");

        jLabel5.setText("Plazo del Prestamo:");

        jLabel6.setText("Interes Anual:");

        jLabel7.setText("Mostrar Tabla en:");

        jLabel8.setText("Tipo de Amortizacion:");

        cNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNombreActionPerformed(evt);
            }
        });
        cNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cNombreKeyTyped(evt);
            }
        });

        cPA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cPAKeyTyped(evt);
            }
        });

        cPlazo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cPlazoKeyTyped(evt);
            }
        });

        cSA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cSAKeyTyped(evt);
            }
        });

        cIA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cIAKeyTyped(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Monto del Prestamo:");

        cMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMontoActionPerformed(evt);
            }
        });
        cMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cMontoKeyTyped(evt);
            }
        });

        tablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Periodo K", "Deuda Inicial", "Intereses", "Amortización", "Cuota"
            }
        ));
        jScrollPane2.setViewportView(tablaResultados);

        jLabel17.setText("Nombre Cliente:");

        jLabel18.setText("Monto del Préstamos:");

        jLabel19.setText("Plazo del Préstamos:");

        jLabel20.setText("Interés anual:");

        jLabel21.setText("Sistema de Amortización:");

        cltNombre.setText(" ");

        JrMonto.setText(" ");

        jrPlazo.setText(" ");

        jrIA.setText(" ");

        jrAmortizacion.setText(" ");

        labelChuky.setText(" ");

        jLabel10.setText("Tipo de cambio compra BCCR:");

        jLabel11.setText("Datos de la Consulta");

        labelTipoCambio.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cNombre)
                            .addComponent(cPA)
                            .addComponent(cSA)
                            .addComponent(cPlazo)
                            .addComponent(cIA)
                            .addComponent(jComboBox1, 0, 144, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cMonto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelChuky, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel17)
                            .addComponent(jLabel10))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cltNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JrMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrPlazo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrAmortizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTipoCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(408, 408, 408))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cSA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(labelTipoCambio))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cltNombre))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(JrMonto))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jrPlazo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jrIA))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jrAmortizacion))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(62, 62, 62)
                        .addComponent(jButton1)
                        .addContainerGap(170, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(labelChuky, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNombreKeyTyped
        // TODO add your handling code here:
        
         int k = (int) evt.getKeyChar();//k = al valor de la tecla presionada   
		        if (k > 47 && k < 58) {//Si el caracter ingresado es una letra
		             evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
		             JOptionPane.showMessageDialog(null, "Por favor ingrese su nombre correctamentente", "Alerta",
	                     JOptionPane.ERROR_MESSAGE);
		        }
        
        
    }//GEN-LAST:event_cNombreKeyTyped

    private void cPAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cPAKeyTyped
        // TODO add your handling code here:
         int k = (int) evt.getKeyChar();//k = al valor de la tecla presionada  
          if (k > 47 && k < 58) {//Si el caracter ingresado es una letra
		             evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
		             JOptionPane.showMessageDialog(null, "Por favor ingrese su primer apellido correctamentente", "Alerta",
	                     JOptionPane.ERROR_MESSAGE);
		        }
    }//GEN-LAST:event_cPAKeyTyped

    private void cSAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cSAKeyTyped
        // TODO add your handling code here:
         int k = (int) evt.getKeyChar();//k = al valor de la tecla presionada  
          if (k > 47 && k < 58) {//Si el caracter ingresado es una letra
		             evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
		             JOptionPane.showMessageDialog(null, "Por favor ingrese su segundo apellido correctamentente", "Alerta",
	                     JOptionPane.ERROR_MESSAGE);
		        }
    }//GEN-LAST:event_cSAKeyTyped

    private void cPlazoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cPlazoKeyTyped
        // TODO add your handling code here:
         int k = (int) evt.getKeyChar();//k = al valor de la tecla presionada    
		         if (k >= 97 && k <= 122 || k >= 65 && k <= 90) {//Si el caracter ingresado es una letra
		             evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
		             JOptionPane.showMessageDialog(null, "Por favor digite números", " Alerta",
		                     JOptionPane.ERROR_MESSAGE);
		        }
        
        
        
        
    }//GEN-LAST:event_cPlazoKeyTyped

    private void cIAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cIAKeyTyped
        // TODO add your handling code here:
        
         int k = (int) evt.getKeyChar();//k = al valor de la tecla presionada    
		         if (k >= 97 && k <= 122 || k >= 65 && k <= 90) {//Si el caracter ingresado es una letra
		             evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
		             JOptionPane.showMessageDialog(null, "Por favor digite números", " Alerta",
		                     JOptionPane.ERROR_MESSAGE);
		        }
    }//GEN-LAST:event_cIAKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (validarVista()){ 
            enviarDatos();
            IControlador control = factorycontrol.crearControlador();
            control.consultarAmortizacion(dtoAmortizacion, dtoCliente);
            //limpiarDatos();
            llenarTabla();
            mostrarDatos();
            labelTipoCambio.setText(control.obtenerTipoCambio());
            labelChuky.setText(control.obtenerFechaBackEnd());       
            if(dtoAmortizacion.GetMoneda().equals("Dolares")){
                dolarizar();
            }
        };
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void cNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNombreActionPerformed

    private void cMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cMontoActionPerformed

    private void cMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cMontoKeyTyped
        // TODO add your handling code here: aaaaa
        
         int k = (int) evt.getKeyChar();//k = al valor de la tecla presionada    
		         if (k >= 97 && k <= 122 || k >= 65 && k <= 90) {//Si el caracter ingresado es una letra
		             evt.setKeyChar((char) KeyEvent.VK_CLEAR);//Limpiar el caracter ingresado
		             JOptionPane.showMessageDialog(null, "Por favor digite números", " Alerta",
		                     JOptionPane.ERROR_MESSAGE);
		        }
        
        
    }//GEN-LAST:event_cMontoKeyTyped

    
    private void SetMonedas() throws IOException, JDOMException{
    ArrayList monedas = Lector.obtenerMonedas();
    String[] array = new String[monedas.size()];
    for(int i = 0; i < array.length; i++) {
       jComboBox1.addItem(monedas.get(i).toString());
    }
    }
   
     private void SetAmortizacion() throws IOException, JDOMException{
    ArrayList amortizacion = Lector.obtenerTiposAmortizaciones();
    String[] array = new String[amortizacion.size()];
    for(int i = 0; i < array.length; i++) {
       jComboBox2.addItem(amortizacion.get(i).toString());
    }
    }
   
    private void enviarDatos(){
        
            
        try{
        dtoCliente.setNombre(cNombre.getText());
        dtoCliente.setPrimerApellido(cPA.getText());
        dtoCliente.setSegundoApellido(cSA.getText());
        
        dtoAmortizacion.SetInteres_anual(Integer.parseInt(cIA.getText()));
        dtoAmortizacion.SetMonto_prestamo( Integer.parseInt(cMonto.getText()));
        dtoAmortizacion.SetPlazo(Integer.parseInt(cPlazo.getText()));
        dtoAmortizacion.SetTipoAmortizacion(jComboBox2.getSelectedItem().toString());
        dtoAmortizacion.SetMoneda(jComboBox1.getSelectedItem().toString());        
    }catch (Exception e){}
        
     }
    
    
    
    private void limpiarDatos(){
     cNombre.setText("");
     cPA.setText("");
     cSA.setText("");
     cMonto.setText("");
     cPlazo.setText("");
     cIA.setText("");
    }
    
    private void mostrarDatos(){
          cltNombre.setText(dtoAmortizacion.getCliente().getNombre() + " " + dtoAmortizacion.getCliente().getPrimerApellido() + " " + dtoAmortizacion.getCliente().getSegundoApellido());
          JrMonto.setText(String.valueOf(dtoAmortizacion.GetMonto_prestamo()) + " de colones");
          jrPlazo.setText(String.valueOf(dtoAmortizacion.GetPlazo()) + "" + " años");
          jrIA.setText(String.valueOf(dtoAmortizacion.GetInteres_anual()) + "" + " %");
          jrAmortizacion.setText(dtoAmortizacion.GetTipoAmortizacion());
    
    }
    
    
  
     private void llenarTabla(){
         
         DecimalFormat decimales = new DecimalFormat("0.00");   
         String [] columnas = {"Periodo K", "Deuda", "Interes", "Amortizacion", "Couta"};
         DefaultTableModel tabla = new DefaultTableModel(null, columnas);
       
            for (int i = 0; i <= dtoAmortizacion.GetPlazo(); i++){
                
                Object[] fila = new Object[5];
                if (i==dtoAmortizacion.GetPlazo()){
                    fila[0] = "Total";
                    fila[1] = decimales.format(0);
                    fila[2] = decimales.format(dtoAmortizacion.getResultadoInteres().getLast());
                    fila[3] = decimales.format(dtoAmortizacion.getResultadoAmortizaciones().getLast());
                    fila[4] = decimales.format(dtoAmortizacion.getResultadoCuota().getLast());
                    tabla.addRow(fila);
                }
                else{
                    fila[0] = i+1;
                    fila[1] = decimales.format(dtoAmortizacion.getResultadoDeuda().get(i));
                    fila[2] = decimales.format(dtoAmortizacion.getResultadoInteres().get(i));
                    fila[3] = decimales.format(dtoAmortizacion.getResultadoAmortizaciones().get(i));
                    fila[4] = decimales.format(dtoAmortizacion.getResultadoCuota().get(i));
                    tabla.addRow(fila);
                }
                tablaResultados.setModel(tabla);
                tablaResultados.setVisible(true);
            }
   
     }
     
      private boolean validarVista(){
          if (Integer.parseInt(cIA.getText()) <= 0){
              JOptionPane.showMessageDialog(null, "El interes anual debe ser mayor a cero", " Alerta",
		                     JOptionPane.ERROR_MESSAGE);
              return false;
        } 
          if(Integer.parseInt(cMonto.getText()) <= 0){
                JOptionPane.showMessageDialog(null, "El monto debe ser mayor a cero", " Alerta",
		                     JOptionPane.ERROR_MESSAGE);
                 return false;
          }
          
           if(Integer.parseInt(cPlazo.getText()) <= 0){
                JOptionPane.showMessageDialog(null, "El plazo debe ser mayor a cero", " Alerta",
		                     JOptionPane.ERROR_MESSAGE);
                 return false;
           }
          return true;
    }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VistaGUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(VistaGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (JDOMException ex) {
                    Logger.getLogger(VistaGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JrMonto;
    private javax.swing.JTextField cIA;
    private javax.swing.JTextField cMonto;
    private javax.swing.JTextField cNombre;
    private javax.swing.JTextField cPA;
    private javax.swing.JTextField cPlazo;
    private javax.swing.JTextField cSA;
    private javax.swing.JLabel cltNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel jrAmortizacion;
    private javax.swing.JLabel jrIA;
    private javax.swing.JLabel jrPlazo;
    private javax.swing.JLabel labelChuky;
    private javax.swing.JLabel labelTipoCambio;
    private javax.swing.JTable tablaResultados;
    // End of variables declaration//GEN-END:variables

    private DTOCliente dtoCliente = new DTOCliente();
    private DTOAmortizacion dtoAmortizacion = new DTOAmortizacion();
    private  FactoryControlador factorycontrol = new FactoryConcretoControlador();
    
    private void dolarizar(){
        DecimalFormat decimales = new DecimalFormat("0.00");
        int cols = tablaResultados.getColumnCount();
        int fils = tablaResultados.getRowCount();
        double tipoCambio =Double.parseDouble(labelTipoCambio.getText());
        for(int i=0; i<fils; i++) {
            for(int j=1; j<cols; j++){
               double temporal =  Double.parseDouble(tablaResultados.getValueAt(i,j).toString().replace(",","."));
               tablaResultados.setValueAt(decimales.format(temporal*tipoCambio), i, j); 
            }
        }
    }
}
